[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Redirect para manejar las rutas de Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
